#!/usr/bin/env python3
"""
Script to run verification for all MNIST FC epsilon configurations,
log the results, and extract summary statistics.

This script:
1. Runs verification for each YAML config file (eps1over255, eps2over255, eps3over255, eps4over255)
2. Logs output to separate log files
3. Extracts results from pickle files and generates a summary CSV
"""

import os
import sys
import subprocess
import pickle
import time
import glob
from pathlib import Path
from datetime import datetime
import csv

# Base directory for the script
SCRIPT_DIR = Path(__file__).parent
COMPLETE_VERIFIER_DIR = SCRIPT_DIR.parent.parent.parent
ABCROWN_SCRIPT = COMPLETE_VERIFIER_DIR / "abcrown.py"

# YAML config files to run
YAML_CONFIGS = [
    "mnist_fc_0.03_adv_trained_eps_1over255.yaml",
    "mnist_fc_0.03_adv_trained_eps_2over255.yaml",
    "mnist_fc_0.03_adv_trained_eps_3over255.yaml",
    "mnist_fc_0.03_adv_trained_eps_4over255.yaml",
]

# Output directories
LOGS_DIR = SCRIPT_DIR / "logs"
RESULTS_DIR = SCRIPT_DIR / "results"
LOGS_DIR.mkdir(exist_ok=True)
RESULTS_DIR.mkdir(exist_ok=True)


def run_verification(yaml_config, log_file):
    """
    Run verification for a given YAML config file.
    
    Args:
        yaml_config: Path to YAML config file
        log_file: Path to log file for output
        
    Returns:
        tuple: (success: bool, result_file: str or None)
    """
    yaml_path = SCRIPT_DIR / yaml_config
    
    if not yaml_path.exists():
        print(f"ERROR: YAML config not found: {yaml_path}")
        return False, None
    
    print(f"\n{'='*80}")
    print(f"Running verification for: {yaml_config}")
    print(f"Log file: {log_file}")
    print(f"{'='*80}\n")
    
    # Change to complete_verifier directory to run abcrown
    cmd = [
        sys.executable,
        str(ABCROWN_SCRIPT),
        "--config",
        str(yaml_path)
    ]
    
    start_time = time.time()
    
    try:
        with open(log_file, 'w') as log:
            log.write(f"Verification started at: {datetime.now().isoformat()}\n")
            log.write(f"Command: {' '.join(cmd)}\n")
            log.write(f"{'='*80}\n\n")
            log.flush()
            
            # Run the verification
            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                cwd=str(COMPLETE_VERIFIER_DIR),
                bufsize=1
            )
            
            # Stream output to both console and log file
            for line in process.stdout:
                print(line, end='')
                log.write(line)
                log.flush()
            
            process.wait()
            elapsed_time = time.time() - start_time
            
            log.write(f"\n{'='*80}\n")
            log.write(f"Verification completed at: {datetime.now().isoformat()}\n")
            log.write(f"Total time: {elapsed_time:.2f} seconds\n")
            log.write(f"Return code: {process.returncode}\n")
            
            if process.returncode != 0:
                log.write(f"ERROR: Verification failed with return code {process.returncode}\n")
                return False, None
            
            return True, None
            
    except Exception as e:
        print(f"ERROR: Exception occurred: {e}")
        with open(log_file, 'a') as log:
            log.write(f"ERROR: Exception occurred: {e}\n")
        return False, None


def find_result_file(yaml_config):
    """
    Find the result pickle file generated by abcrown.
    The filename is generated based on config parameters.
    
    Args:
        yaml_config: Name of YAML config file
        
    Returns:
        Path to result file or None if not found
    """
    # Result files are typically saved in the current directory or logs directory
    # They have names like: a-b-crown_[csv_name]_start=0_end=100_...
    # Let's search for .npz files that match the pattern
    
    search_dirs = [
        COMPLETE_VERIFIER_DIR,
        LOGS_DIR,
        RESULTS_DIR,
    ]
    
    # Extract epsilon value from config name to help identify the file
    eps_value = None
    if "1over255" in yaml_config:
        eps_value = "1over255"
    elif "2over255" in yaml_config:
        eps_value = "2over255"
    elif "3over255" in yaml_config:
        eps_value = "3over255"
    elif "4over255" in yaml_config:
        eps_value = "4over255"
    
    # Search for result files
    for search_dir in search_dirs:
        if not os.path.exists(search_dir):
            continue
            
        # Look for .npz files (pickle format used by abcrown)
        pattern = f"*mnistfc_instances_eps{eps_value}*.npz"
        matches = glob.glob(str(Path(search_dir) / pattern))
        
        if matches:
            # Return the most recently modified file
            matches.sort(key=os.path.getmtime, reverse=True)
            return matches[0]
    
    return None


def extract_results(result_file):
    """
    Extract results from a pickle file generated by abcrown.
    Note: Files have .npz extension but are actually pickle files.
    
    Args:
        result_file: Path to result pickle file
        
    Returns:
        dict: Extracted results with summary statistics
    """
    if result_file is None or not os.path.exists(result_file):
        return None
    
    try:
        # Try pickle first (even though extension is .npz)
        try:
            with open(result_file, 'rb') as f:
                data = pickle.load(f)
        except (pickle.UnpicklingError, EOFError):
            # If pickle fails, try numpy format
            import numpy as np
            data = dict(np.load(result_file, allow_pickle=True))
        
        summary = data.get('summary', {})
        results = data.get('results', [])
        bab_ret = data.get('bab_ret', [])
        
        # Count results by status
        status_counts = {}
        total_time = 0.0
        verified_count = 0
        falsified_count = 0
        unknown_count = 0
        timeout_count = 0
        
        for status, indices in summary.items():
            status_counts[status] = len(indices)
            if 'verified' in status.lower() or 'safe' in status.lower() or 'unsat' in status.lower():
                verified_count += len(indices)
            elif 'falsified' in status.lower() or 'unsafe' in status.lower() or 'sat' in status.lower():
                falsified_count += len(indices)
            elif 'unknown' in status.lower():
                unknown_count += len(indices)
            elif 'timeout' in status.lower() or 'timed out' in status.lower():
                timeout_count += len(indices)
        
        # Calculate total time
        for result in results:
            if len(result) >= 2:
                total_time += result[1]  # result[1] is the time
        
        # Calculate average time
        avg_time = total_time / len(results) if results else 0.0
        
        return {
            'total_instances': len(results),
            'verified': verified_count,
            'falsified': falsified_count,
            'unknown': unknown_count,
            'timeout': timeout_count,
            'status_counts': status_counts,
            'total_time': total_time,
            'avg_time': avg_time,
            'results': results,
            'bab_ret': bab_ret
        }
        
    except Exception as e:
        print(f"ERROR: Failed to extract results from {result_file}: {e}")
        return None


def generate_summary_csv(all_results, output_file):
    """
    Generate a CSV summary of all verification results.
    
    Args:
        all_results: Dict mapping config names to extracted results
        output_file: Path to output CSV file
    """
    with open(output_file, 'w', newline='') as f:
        writer = csv.writer(f)
        
        # Header
        writer.writerow([
            'Config',
            'Epsilon',
            'Total Instances',
            'Verified',
            'Falsified',
            'Unknown',
            'Timeout',
            'Total Time (s)',
            'Avg Time (s)',
            'Result File'
        ])
        
        # Data rows
        for config_name, results in sorted(all_results.items()):
            if results is None:
                writer.writerow([config_name, 'N/A', 'ERROR', '', '', '', '', '', '', ''])
                continue
            
            # Extract epsilon from config name
            eps = 'N/A'
            if '1over255' in config_name:
                eps = '1/255'
            elif '2over255' in config_name:
                eps = '2/255'
            elif '3over255' in config_name:
                eps = '3/255'
            elif '4over255' in config_name:
                eps = '4/255'
            
            writer.writerow([
                config_name,
                eps,
                results['total_instances'],
                results['verified'],
                results['falsified'],
                results['unknown'],
                results['timeout'],
                f"{results['total_time']:.2f}",
                f"{results['avg_time']:.4f}",
                results.get('result_file', 'N/A')
            ])
    
    print(f"\nSummary CSV saved to: {output_file}")


def main():
    """Main function to run all verifications and extract results."""
    print("="*80)
    print("MNIST FC Verification Runner")
    print("="*80)
    print(f"Script directory: {SCRIPT_DIR}")
    print(f"Complete verifier directory: {COMPLETE_VERIFIER_DIR}")
    print(f"ABCROWN script: {ABCROWN_SCRIPT}")
    print(f"Logs directory: {LOGS_DIR}")
    print(f"Results directory: {RESULTS_DIR}")
    print(f"\nConfigurations to run: {len(YAML_CONFIGS)}")
    for config in YAML_CONFIGS:
        print(f"  - {config}")
    print("="*80)
    
    all_results = {}
    
    # Run verification for each config
    for yaml_config in YAML_CONFIGS:
        # Create log file name
        log_name = yaml_config.replace('.yaml', '.log')
        log_file = LOGS_DIR / log_name
        
        # Run verification
        success, result_file = run_verification(yaml_config, log_file)
        
        if success:
            # Try to find the result file
            result_file = find_result_file(yaml_config)
            if result_file:
                print(f"Found result file: {result_file}")
            else:
                print(f"WARNING: Could not find result file for {yaml_config}")
            
            # Extract results
            results = extract_results(result_file)
            if results:
                results['result_file'] = result_file
                results['log_file'] = str(log_file)
            all_results[yaml_config] = results
        else:
            print(f"ERROR: Verification failed for {yaml_config}")
            all_results[yaml_config] = None
    
    # Generate summary CSV
    summary_csv = RESULTS_DIR / f"verification_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
    generate_summary_csv(all_results, summary_csv)
    
    # Print summary
    print("\n" + "="*80)
    print("VERIFICATION SUMMARY")
    print("="*80)
    for config_name, results in sorted(all_results.items()):
        print(f"\n{config_name}:")
        if results is None:
            print("  ERROR: Failed to extract results")
        else:
            print(f"  Total instances: {results['total_instances']}")
            print(f"  Verified: {results['verified']}")
            print(f"  Falsified: {results['falsified']}")
            print(f"  Unknown: {results['unknown']}")
            print(f"  Timeout: {results['timeout']}")
            print(f"  Total time: {results['total_time']:.2f}s")
            print(f"  Avg time: {results['avg_time']:.4f}s")
            if 'result_file' in results:
                print(f"  Result file: {results['result_file']}")
    
    print("\n" + "="*80)
    print(f"All results saved to: {RESULTS_DIR}")
    print(f"Summary CSV: {summary_csv}")
    print("="*80)


if __name__ == "__main__":
    main()

